basket/urls.py
from basket import views
from django.urls import path
#basket/create
#basket/players
#basket/

app_name = 'basket'

urlpatterns = [
    path('', views.home, name='home'),
    #path('login/', views.auth_login, name='auth'),
    path('base/', views.base, name='base'),
    path('players', views.players, name='players'),
    path('players/list', views.players_list, name='players_list'),
    path('coach/', views.coach, name='coach'),
    path('list_team/', views.list_team, name='teams'),
    path('match/', views.match, name='match'),
    #path('CoachList/', views.coach, name="coach"),
    path('create/player/', views.create_player, name="create_player"),
    path('update/player/<int:player_id>', views.update_player, name='update_player'),
    path('delete/player/<int:player_id>', views.delete_player, name='delete_player'),

    path('create/coach/', views.create_coach, name='create_coach'),
    path('update/coach/<int:coach_id>', views.update_coach, name="update_coach"),
    path('delete/coach/<int:coach_id>', views.delete_coach, name='delete_coach'),

    path('create/teams/', views.create_team, name='create_teams'),
    path('update/teams/<int:team_id>', views.update_teams, name='update_teams'),
    path('delete/team/<int:team_id>', views.delete_team, name='delete_team')

    #path('delete/<int:basket_id', views.delete, name='delete')

]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #path('', views.home, name='home'), #path('', ) vacio hace referencia a la raiz del sitio o portadaº
    path('admin/', admin.site.urls),
    path('basket/', include('basket.urls')),
    path('auth/', include('auth_login.urls'))


]

#iteracion pada poder ver imagenes en el backend de django
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

basket/models.py
from django.db import models
from django.utils.safestring import mark_safe

# Create your models here.

"""
Coach
name
age
email
rut
nickname
"""
class Coach(models.Model):
	name = models.CharField(max_length=150)
	age = models.PositiveIntegerField()
	email = models.EmailField()
	rut = models.CharField(max_length=12)
	nickname = models.CharField(max_length=80)

	def __str__(self):
		return self.name


"""
Team
name
description
code
logo
"""
class Team(models.Model):
	name = models.CharField(max_length=150)
	description = models.TextField()
	# code tendra un valor unico -> unique=True
	code = models.CharField(max_length=20, unique=True)
	#logo es ImageFiel y se debe cargar en folder -> upload='teams/'
	logo = models.ImageField(upload_to='teams/')
	#coach tiene relacion 1:1
	coach = models.OneToOneField(Coach, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

#para crear opciones desplegables se crean con tuplas y sub tuplas
POSITION_PLAYER = (
	('BA', 'Base'),
	('ES', 'Escolta'),
	('AL', 'Alero'),
	('AP', 'Ala-Pivot'),
	('PI', 'Pivot'),
)

class Player(models.Model):
	name = models.CharField(max_length=150)
	nickname = models.CharField(max_length=80)
	birthday = models.DateField()
	age = models.PositiveIntegerField()
	rut = models.CharField(max_length=12)
	email = models.EmailField()
	height = models.PositiveIntegerField(help_text='en centimetros')
	weight = models.PositiveIntegerField(help_text='in grams')
	photo = models.ImageField(upload_to='players/')
	#max_lenght=2 es porque en PISITION_PLAYER estan declarados dos strings -> BA, Base
	position = models.CharField(choices=POSITION_PLAYER, max_length=2)
	#declaramos la relacion 1:n referenciando a Player
	#la FK esta relacionando los jugadores con el equipo
	#3l primer valor seria el modelo al cual lo voy a relacionar
	team = models.ForeignKey(Team, on_delete=models.CASCADE)

	def __str__(self):
		return '{name} ({team})'.format(name=self.name, team=self.team)


#clase nomina Roster, mostrara los nombres de los jugadores nominados a un partido
#la relacionamons con la clase Palver y su cardinalidad es n:n
class Roster(models.Model):
	name = models.CharField(max_length=150)
	player = models.ManyToManyField(Player, help_text='Mantenga presionado "Control" o "Command" en Mac '
													  'para seleccionar más de un jugador, ')

	def __str__(self):
		return self.name


#crearemos la clase Match para armar los juegos que se agregaron en Roster(alineados de convocados)
#los Match ( partidos se gueran enrtre dos equipos -> Team1 y Team"
#los Match (partidos contienen una fecha del timpo DateTimeField)
#no se pueddn declarar dos ForeignKey -> se usa ManyToMany y solo lleva un argumento
class Match(models.Model):
	name = models.CharField(max_length=150)
	#teams = models.ManyToManyField(Roster)
	team1 = models.ForeignKey(Roster, related_name='team1', on_delete=models.CASCADE)
	team2 = models.ForeignKey(Roster, related_name='team2', on_delete=models.CASCADE)
	date = models.DateTimeField()

	def	__str__(self):
		return '{name} ({team2} vs {team2})'.format(
			name=self.name,
			team1=self.team1,
			team2=self.team2
		)

basket/forms.py
from django import forms
from basket.models import Coach, Player, Team


class PlayersForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = '__all__'


class CoachForm(forms.ModelForm):
    class Meta:
        model = Coach
        fields = '__all__'


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'


class ProfileForm(forms.Form):
    mail = forms.EmailField(label='Email', max_length=50)
    password = forms.CharField(max_length=20)

basket/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.paginator import (Paginator,
                                   EmptyPage, 
                                   PageNotAnInteger)
from basket.models import Player, Coach, Team, Match
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import ListView, CreateView
from basket.forms import PlayersForm, TeamForm, CoachForm
# Create your views here.

@login_required
def home(request):
    data = {}
    template_name = 'home.html'
    #ata['title'] = 'Este es el Home'
    #ata['players'] = Player.objects.all().order_by('-team')[:5]
    #data.players.count()
    data['last_5_matchs'] = Match.objects.all().order_by('-pk')[:3]
    data['last_5_players'] = Player.objects.all().order_by('-pk')[:3]
    data['teams'] = Team.objects.all()

    return render(request, template_name, data)

@login_required
def players_list(request):
    data = {}
    template_name = 'players_list.html'
    #data['players'] = Player.objects.all()

    teams = Team.objects.all()

    for team in teams:
        team.players = Player.objects.filter(team=team)

    data['teams'] = teams

    '''
    print('------------------')
    for team in teams:
        print(team.name)
        print('-------')
        for player in team.players:
            print(player.name)
        print('-------')
    '''
    return render(request, template_name, data)

@login_required
def players(request):
    data = {}
    template_name = 'players_list.html'
    #data['title'] = 'Players List'
    data['players'] = Player.objects.all()

    players = Player.objects.all()
    teams = Team.objects.all()

    for team in teams:
        teams.players = Player.objects.filter(team=team)

        data['teams'] = teams

    return render(request, template_name, data)


@login_required
def coach(request):

    print("PERMISOS")
    print(request.user.has_perm('basket.change_coach'))
    data = {}
    template_name = 'coach.html'

    print("User Login: ", request.user.pk)
    print("User Login", request.user.username)
    
    #data['title'] = 'Lista de entrenadores!!'
    data['coach'] = Coach.objects.all().order_by('-pk')[:3]


    return render(request, template_name, data)

def match(request):
    data = {}
    template_name = 'match.html'
    data['title'] = 'Lista de Matchs'
    data['match'] = Match.objects.all()

    return render(request, template_name, data)
"""
def poll_list(request):
    template_name = 'contacto.html'
    data = {}
    #traer todos los objetos de Player
    data['title'] = 'Lists Players from poll_list'
    #consulta con filtro juan
    data['jugadores'] = Player.objects.filter(
        name__contains='juan'
    )

    data['jugadores'] = Player.objects.all()

    return render(request, template_name, data)

"""


"""
def home(request):
    template_name = 'home.html'
    data = {}
    data['title'] = "Lista de jugadores desde home"
    data['players'] = Coach.objects.all()

    return render(request, template_name, data)
"""


#pagination in django
@login_required
def list_team(request):
    data = {}
    template_name = 'teams.html'

    data['title'] = "Lista de equipos indexados"

    page = request.GET.get('page', 1)
    #player_lists = Player.objects.all()
    team_lists = Team.objects.all()

    paginator = Paginator(team_lists, 3)

    try:
        data['teams'] = paginator.page(page)
    except PageNotAnInteger:
        data['teams'] = paginator.page(1)
    except EmptyPage:
        data['teams'] = paginator.page(paginator.num_pages)

    #paginator = Paginator(player_lists, 3)

    '''
    try:
        data['players'] = paginator.page(page)
    except PageNotAnInteger:
        data['players'] = paginator.page(1)
    except EmptyPage:
        data['players'] = paginator.page(paginator.num_pages)
    '''
    return render(request, template_name, data)


@login_required
def base(request):
    template_name = 'base.html'
    data={}
    data['title'] = "Desde la Base"

    return render(request, template_name)


@login_required
def create(request):
    data = {}
    template_name = 'create_coach.html'

    data['form'] = PlayersForm(request.POST or None)

    #aca se valida y se guarda el formulario
    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:players')

    return render(request, template_name, data)


@permission_required('basket.add_coach')
def create_coach(request):
    data = {}
    template_name = 'create_coach.html'

    data['form'] = CoachForm(request.POST or None)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:coach')

    return render(request, template_name, data)


@permission_required('basket.change_coach')
def update_coach(request, coach_id):
    template_name = 'update_coach.html'
    data = {}
    
    coach = Coach.objects.get(pk=coach_id)
    data['form'] = CoachForm(request.POST or None, instance=coach)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:coach')

    return render(request, template_name, data)


@permission_required('basket.delete_coach')
def delete_coach(request, coach_id):
    data = {}
    data['coach'] = Player.objects.get(pk=coach_id)

    if request.method == 'POST':
        data['coach'].delete()
        return redirect('basket:players')

    template_name = 'delete_coach.html'

    return render(request, template_name, data)


@login_required
def create_player(request):
    data = {}
    template_name = 'create_player.html'

    data['form'] = PlayersForm(request.POST or None, request.FILES)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:player_list')

    return render(request, template_name, data)


@login_required
def update_player(request, player_id):
    template_name = 'update_player.html'
    data = {}

    player = Player.objects.get(pk=player_id)
    data['form'] = PlayersForm(request.POST or None, instance=player)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:players')

    return render(request, template_name, data)


@login_required
def delete_player(request, player_id):
    data = {}
    data['player'] = Player.objects.get(pk=player_id)

    if request.method == 'POST':
        data['player'].delete()
        return redirect('basket:players')
        
    template_name = 'delete_player.html'

    return render(request, template_name, data)


@login_required
def create_team(request):
    data = {}
    template_name = 'create_teams.html'

    data['form'] = TeamForm(request.POST or None, request.FILES)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:teams')

    return render(request, template_name, data)


@login_required
def update_teams(request, team_id):
    template_name = 'update_teams.html'
    data = {}

    team = Team.objects.get(pk=team_id)
    data['form'] = TeamForm(request.POST or None, instance=team)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('basket:teams_list')
    else:
        print("error al guardar")

    return render(request, template_name, data)


@login_required
def delete_team(request, team_id):
    data= {}
    data['team'] = Team.objects.get(pk=team_id)

    if request.method == 'POST':
        data['team'].delete()
        return redirect('basket:players')

    template_name = 'delete_team.html'

    return render(request, template_name, data)


#se agrega el coach profile
def profile_coach(request):
    template_name = 'profile_coach.html'
    data = {}

    return render(request, template_name, data)

basket/templates/coach.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block title %}Entrenadores{% endblock %}
{% block extra_css %}
<style>
    .color_update_coach {
        color: #F3EC11;
        font-size: 22px;
    }
    .color_delete_coach {
        color: #F51809;
        font-size: 22px;
    }
</style>
{% endblock %}

{% block content %}
<!DOCTYPE html>
<html5 lang="es-cl">

<head>

<head class="container">

    <div class="row mt-3">

        <img class="mb-4" src="{% static 'core/img/basketball-coach.jpg' %}" alt="" width="52" height="52">

        <div class="col-md-9 col-lg-10">
            <h3>Lista de Entrenadores</h3>
        </div>
        <div class="col-md-3 col-lg-2">
            {% if request.user.is_superuser %}
            <a href="{% url 'basket:create_coach' %}" class="btn btn-success btn-block mt-3"><i class="fas fa-plus-square"></i> Entrenador</a>
            {% endif %}
        </div>
    </div>
</head>

<body>
    <body>
        <table class="table">
        <thead class="thead-dark">
        <tr>
            <th style="color: white">Name</th>
            <th style="color: white">Team</th>

        {% if request.user.is_superuser %}
        <th style="color: white">Actions</th>
        </tr>
        {% endif %}
        </thead>
                <tbody_>
                   <tr>
                {% for coach in coach %}
                <tr>
                    <td>{{coach.name}} (<strong>{{coach.team.name}}</strong>)</td>
                    <td>{{coach.team.name}} (<strong>{{coach.team.name}}</strong>)</td>
                    {% if request.user.is_superuser %}
                    <td>
                        <a href="{% url 'basket:update_coach' coach.id %}"><i class="fas fa-edit color_update_coach"></i></a> |
                        <a href="{% url 'basket:delete_coach' coach.id %}"><i class="fas fa-trash-alt color_delete_coach"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody_>
        </table>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/98a2688348.js" crossorigin="anonymous"></script>
    </body>
</body>
{% endblock %}

basket/templates/delete_coach.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}delete coach{% endblock %}
{% block content %}

<nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'basket:home' %}"><i class="fas fa-home"></i></a></li>
        <li class="breadcrumb-item"><a href="{% url 'basket:coachs_list' %}">Coachs</a></li>
        <li class="breadcrumb-item active" aria-current="page">Delete Coach</li>
        </ol>
    </nav>
  <h2>Delete Coach</h2>
  {% bootstrap_messages %}
</head>

<body>
	<p>¿Estas seguro que quieres eliminar a <strong>{{coach.name}}</strong>?</p>
	<form class="" method="post">
		{% csrf_token %}

		<input type="submit" name="" class="btn btn-danger" value="Eliminar">|<a href="{% url 'basket:coachs_list' %}" class="btn btn-light">Cancelar</a>


	</form>
{% endblock %}

basket/templates/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<!DOCTYPE html>
<html5 lang="es-cl">
<head>
    <!-- Require meta tags-->
    <meta charset="UTF-8">
    <title>Home</title>
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<h1>Links</h1>
    <ul>
        <li><a href="{% url 'basket:home' %}">Home</a></li>
        <li><a href="{% url 'basket:teams' %}">Teams</a></li>
        <li><a href="{% url 'basket:match' %}">Matches</a></li>

    </ul>

    {% block link %}{% endblock %}

<div class="row">
    <table class="table table-hover mt-3">
        <thead class="thead-dark">
        <th style="color: white">Last 3 Matchs</th>
        <th style="color: white">Position</th>
        </thead>
</div>
<tr>
    {% for match in last_5_matchs %}
        <tr>
            <td style="color: black">{{ match.team1.player.first.team.name }} <strong>VS </strong>{{ match.team2.player.first.team.name }}</td>
            <td style="color: black">{{ match.date }}</td>
        <tr>
    {% endfor %}
    </tr>
</table>

<table class="table mt-2">
    <thead class="thead-dark">
    <th style="color: white">Last 3 Players</th>
    <th style="color: white">Position</th>
    </thead>
    <tr>
                {% for player  in last_5_players %}
            <tr>
                <td style="color: black">{{ player.name }} ({{ player.nickname }})</td>
                <td style="color: black">{{ player.position }} ({{ player.postion }})</td>
            <tr>
        {% endfor %}
        </tr>
</table>

<table class="table mt-2">
    <thead class="thead-dark">
        <th style="color: white">Teams</th>
    </thead>
</div>

</table>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/6a748a1171.js" crossorigin="anonymous"></script>
</body>

</html5>

{% endblock %}

basket/templates/players_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Lista de Jugadores{% endblock %}

<html lang="es-cl">

    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <title>Player list</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    {% block extra_css %}
<style>
	.color_update_player {
		color: #F3EC11;
		font-size: 22px;
	}
	.color_delete_player {
		color: #F51809;
		font-size: 22px;
	}
</style>
{% endblock %}


{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'basket:home' %}"><i class="fas fa-home"></i></a></li>
        <li class="breadcrumb-item active" aria-current="page">Player</li>
        </ol>
    </nav>


<head>

    <div class="row mt-3">
        <div class="col-md-9 col-lg-10">
            <h3>Lista de Jugadores</h3>
        </div>
    <div class="col-md-3 col-lg-2">
        <a href="{% url 'basket:create_player' %}" class="btn btn-success btn-block mt-3"><i class="fas fa-plus-square"></i> Create Player</a>
    </div>
    </div>
</head>
    <body>
    <table class="table table-hover mt-3">
        {% for team in teams %}

            <tr>
            <thead class="thead-dark">
                <th style="color: white">{{team.name}}</th>
                <th style="color: white">Acción</th>

            </thead>
            </div>

            {% for player in team.players %}
            <tr>
                <td>{{player.name}}</td>
                <td>
                    <a href="{% url 'basket:update_player' player.id %}"><i class="fas fa-edit color_update_player"></i></a> |
                    <a href="{% url 'basket:delete_player' player.id %}"><i class="fas fa-trash-alt color_delete_player"></i></a>
                </td>
            </tr>
                {% endfor %}
            <tr>
                {% endfor %}
            </tr>
    </table>
    {% buttons %}
        <button type="submit" class="btn btn-primary btn-lg">
            <i class="far fa-edit"></i>Actualizar Jugador
        </button>
        {% endbuttons %}
    </body>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </html>
{% endblock %}

basket/templates/teams.html
{% extends "base.html" %}
{% block title %}Equipos{% endblock %}

<html lang="es-cl">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{% block content %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    {% block extra_css %}
	<style>
	.color_update_team {
		color: #F3EC11;
		font-size: 22px;
	}
	.color_delete_team {
		color: #F51809;
		font-size: 22px;
	}
	</style>
{% endblock %}


	 <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'basket:home' %}"><i class="fas fa-home"></i></a></li>
        <li class="breadcrumb-item active" aria-current="page">Team</li>
        </ol>
    </nav>


     <head>
    <div class="container">

        <div class="row mt-3">
        	<div class="col-md-9 col-lg-10">
        		<h3> LIST TEAMS </h3>
			</div>
        	<div class="col-md-3 col-lg-2">
        		<a href="{% url 'basket:create_teams' %}" class="btn btn-success btn-block mt-3"><i class="fas fa-plus-square"></i> Crear Equipo</a>

			</div>
		</div>

	</div>
	<body>
        	<table class="table table-hover mt-4">
        		<thead class="thead-dark">
            		<th style="color: white">Teams</th>
            		<th style="color: white">Coach</th>
            		<th style="color: white">Acción</th>
        		</thead>
            <div>
                <tr>
        			{% for team in teams %}
        		<tr>
        			<td>{{team.name}}</td>
        			<td>{{team.coach}}</td>
        			<td><a href="{% url 'basket:update_teams' team.id %}"><i class="fas fa-edit color_update_team"></i></a> |
        			<a href="{% url 'basket:delete_team' team.id %}"><i class="fas fa-trash-alt color_delete_team"></i></a></td>


        		</tr>
        			{% endfor %}
    		</div>
    		</table>

			<hr>

   			{% if teams.has_other_pages %}
   			<nav aria-label="Page navigation">
  			<ul class="pagination">
    		{% if teams.has_previous %}
      		<li class="page-item"><a href="?page={{ teams.previous_page_number }}" class="page-link">&laquo;</a></li>
   			{% else %}
      		<li class="page-item" class="disabled"><span class="page-link">&laquo;</span></li>
    		{% endif %}

    		{% for i in teams.paginator.page_range %}
      		{% if teams.number == i %}
        	<li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      		{% else %}
        	<li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      		{% endif %}
    		{% endfor %}


    		{% if teams.has_next %}
      		<li><a href="?page={{ teams.next_page_number }}" class="page-link">&raquo;</a></li>
    		{% else %}
      		<li class="disabled"><span class="page-link">&raquo;</span></li>
    		{% endif %}
  			</ul>
  			</nav>
			{% endif %}

	</body>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>
{% endblock %}